<?php

return [
    'subscription_features' => [
        ['value' => 'dashboard', 'label' => 'Dashboard'],
        ['value' => 'pos', 'label' => 'Point of Sales'],
        ['value' => 'service', 'label' => 'Servis'],
        ['value' => 'warranty', 'label' => 'Garansi'],
        ['value' => 'product', 'label' => 'Produk'],
        ['value' => 'purchase', 'label' => 'Pembelian'],
        ['value' => 'stock', 'label' => 'Pergerakan Stok'],
        ['value' => 'finance', 'label' => 'Keuangan'],
        ['value' => 'hrd', 'label' => 'HRD'],
        ['value' => 'payroll', 'label' => 'Payroll'],
        ['value' => 'customers', 'label' => 'Customers'],
        ['value' => 'suppliers', 'label' => 'Suppliers'],
        ['value' => 'users', 'label' => 'Users'],
        ['value' => 'roles', 'label' => 'Roles & Permissions'],
        ['value' => 'settings', 'label' => 'Pengaturan'],
        ['value' => 'tenants', 'label' => 'Tenant'],
    ],
    'subscription_feature_permissions' => [
        'dashboard' => ['dashboard.view'],
        'pos' => ['pos.access', 'pos.create', 'pos.print'],
        'service' => ['service.access', 'service.create', 'service.update_status', 'service.add_sparepart'],
        'warranty' => ['warranty.view', 'warranty.claim', 'warranty.approve'],
        'product' => ['inventory.view', 'inventory.create', 'inventory.update'],
        'purchase' => ['purchase.view', 'purchase.create', 'purchase.approve'],
        'stock' => ['inventory.adjust_stock'],
        'finance' => ['finance.view', 'finance.create_income', 'finance.create_expense', 'finance.close_cash', 'finance.report'],
        'hrd' => ['hrd.manage'],
        'payroll' => ['payroll.manage'],
        'customers' => ['customer.manage'],
        'suppliers' => ['supplier.manage'],
        'users' => ['user.manage'],
        'roles' => ['role.manage', 'permission.manage'],
        'settings' => ['settings.view', 'settings.update'],
        'tenants' => ['tenant.manage'],
    ],
];
