<?php

return [
    'subscription_features' => [
        ['value' => 'dashboard', 'label' => 'Dashboard'],
        ['value' => 'customers', 'label' => 'Customers'],
        ['value' => 'suppliers', 'label' => 'Suppliers'],
        ['value' => 'inventory_categories', 'label' => 'Kategori Produk'],
        ['value' => 'inventory_products', 'label' => 'Produk'],
        ['value' => 'purchases', 'label' => 'Pembelian'],
        ['value' => 'stock_movements', 'label' => 'Pergerakan Stok'],
        ['value' => 'finance', 'label' => 'Keuangan'],
        ['value' => 'pos', 'label' => 'Point of Sales'],
        ['value' => 'service', 'label' => 'Servis'],
        ['value' => 'users', 'label' => 'Users'],
        ['value' => 'roles_permissions', 'label' => 'Roles & Permissions'],
        ['value' => 'settings', 'label' => 'Pengaturan'],
        ['value' => 'warranty_list', 'label' => 'Daftar Garansi'],
        ['value' => 'warranty_reminder', 'label' => 'Reminder Garansi'],
        ['value' => 'warranty_claim', 'label' => 'Klaim Garansi'],
        ['value' => 'whatsapp_broadcast', 'label' => 'Broadcast WhatsApp'],
        ['value' => 'whatsapp_templates', 'label' => 'Template Pesan WhatsApp'],
        ['value' => 'whatsapp_logs', 'label' => 'Log Pengiriman WhatsApp'],
        ['value' => 'tenants', 'label' => 'Tenant'],
        ['value' => 'tenant_management', 'label' => 'Manajemen Tenant'],
    ],
    'subscription_feature_permissions' => [
        'dashboard' => ['dashboard.view'],
        'customers' => ['customer.manage'],
        'suppliers' => ['supplier.manage'],
        'inventory_categories' => ['inventory.view', 'inventory.update'],
        'inventory_products' => ['inventory.view', 'inventory.create', 'inventory.update'],
        'stock_movements' => ['inventory.adjust_stock'],
        'purchases' => ['purchase.view', 'purchase.create', 'purchase.approve'],
        'finance' => ['finance.view', 'finance.create_income', 'finance.create_expense', 'finance.close_cash', 'finance.report'],
        'pos' => ['pos.access', 'pos.create', 'pos.print'],
        'service' => ['service.access', 'service.create', 'service.update_status', 'service.add_sparepart'],
        'users' => ['user.manage'],
        'roles_permissions' => ['role.manage', 'permission.manage'],
        'settings' => ['settings.view', 'settings.update'],
        'warranty_list' => ['warranty.view'],
        'warranty_reminder' => ['warranty.view'],
        'warranty_claim' => ['warranty.claim', 'warranty.approve'],
        'whatsapp_broadcast' => ['whatsapp.broadcast'],
        'whatsapp_templates' => ['whatsapp.template_manage'],
        'whatsapp_logs' => ['whatsapp.log_view'],
        'tenants' => ['tenant.manage'],
        'tenant_management' => ['tenant.manage'],
    ],
];
